# CustomJoinMessage 统一配置文件
# 支持 Velocity/BungeeCord + Paper/Spigot/Folia 多平台

# ================================
# 插件基础设置
# ================================
plugin:
  # 运行模式 (standalone, backend)
  # standalone: 后端独立模式（完整功能）
  # backend: 后端从属模式（仅拦截消息）
  # 注意：代理端会自动启用主控模式，无需配置
  mode: "backend"
  
  # 调试模式（包含详细日志信息）
  debug: false

# ================================
# 功能开关
# ================================
features:
  # 欢迎消息
  welcome-message:
    # 首次加入欢迎消息
    first-time-enabled: true
    first-time-delay: 500  # 延迟发送（毫秒）
    
    # 回归玩家欢迎消息
    returning-enabled: true
    returning-threshold: "1d"   # 多久没上线会触发回归消息（支持: 1d2h30m格式，默认1天）
  
  # 服务器切换消息
  server-switch-message:
    enabled: true
    show-to-all: true  # 是否向所有玩家显示
  
  # 自定义加入格式
  custom-join-format:
    enabled: true
  
  # 自定义离开格式
  custom-leave-format:
    enabled: true
  
  # 首次加入特殊处理
  first-join:
    enabled: true
    different-message: true

# ================================
# 消息拦截设置
# ================================
interception:
  # 拦截系统加入消息
  intercept-join-messages: true
  
  # 拦截系统离开消息
  intercept-leave-messages: true

# ================================
# 服务器别名配置（仅代理端使用）
# ================================
server-aliases:
  # 服务器名称映射到友好的中文别名
  # 格式：服务器名: "显示别名"
  # 示例配置（取消注释并修改为你的服务器名称）：
  # survival: "生存服"
  # creative: "创造服"
  # pvp: "PVP竞技场"
  # lobby: "大厅"
  # skyblock: "空岛服"
  # minigames: "小游戏"
  # build: "建筑服"
  # economy: "经济服"

# ================================
# 权限组配置（智能权限检测）
# ================================
permission-groups:
  # 权限组优先级（数字越大优先级越高）
  # 当玩家拥有多个权限时，会选择优先级最高的权限组
  # 权限节点格式：customjoinmessage.权限组名（default组无权限要求）
  priority:
    default: 0     # 默认组，所有玩家都有
    vip: 10
    # moderator: 20
    # admin: 30
    # mvp: 15

# ================================
# 消息模板配置（按权限组分组）
# ================================
messages:
  # 默认权限组（无特殊权限的玩家）
  default:
    # 玩家加入消息
    join:
      # 标准加入消息
      default: "<green>✅ <yellow>{player}</yellow> 加入了服务器！</green>"
      
      # 首次加入消息
      first-time: "<green>欢迎新玩家 <yellow>{player}</yellow> 首次加入服务器！</green>"
      
      # 回归玩家加入消息
      returning: "<blue>老朋友 <yellow>{player}</yellow> 回来了！</blue>"
    
    # 玩家离开消息
    leave:
      # 标准离开消息
      default: "<red>❌ <yellow>{player}</yellow> 离开了服务器！</red>"
    
    # 欢迎消息（发送给加入的玩家）
    welcome:
      # 首次加入欢迎消息
      first-time: |
        <yellow>================================</yellow>
        <green>欢迎新玩家 {player}！</green>
        <blue>这是你第一次加入我们的服务器</blue>
        <gray>输入 /help 查看帮助信息</gray>
        <gray>当前在线：{online_count}/{max_players}</gray>
        <yellow>================================</yellow>
      
      # 回归玩家欢迎消息
      returning: |
        <yellow>================================</yellow>
        <green>欢迎回来，{player}！</green>
        <gray>你上次游戏时间：{last_seen}</gray>
        <gray>当前在线：{online_count}/{max_players}</gray>
        <yellow>================================</yellow>

    # 服务器切换消息（代理端）
    server-switch:
      # 基本切换消息格式
      default: "<gray>📡 {player} 从 <yellow>{from}</yellow> 切换到 <yellow>{to}</yellow></gray>"

  vip:
    join:
      default: "<gold>⭐ VIP玩家 <yellow>{player}</yellow> 加入了服务器！</gold>"
      first-time: "<gold>欢迎VIP新玩家 <yellow>{player}</yellow> 首次加入服务器！</gold>"
      returning: "<gold>VIP老朋友 <yellow>{player}</yellow> 荣耀回归！</gold>"
    leave:
      default: "<gold>⭐ VIP玩家 <yellow>{player}</yellow> 离开了服务器！</gold>"
    welcome:
      first-time: |
        <gold>================================</gold>
        <yellow>欢迎VIP新玩家 {player}！</yellow>
        <blue>感谢您对服务器的支持！</blue>
        <gray>您享有VIP专属权限和福利</gray>
        <gray>当前在线：{online_count}/{max_players}</gray>
        <gold>================================</gold>
      returning: |
        <gold>================================</gold>
        <yellow>欢迎VIP玩家 {player} 回归！</yellow>
        <gray>您上次游戏时间：{last_seen}</gray>
        <blue>您的VIP权限依然有效</blue>
        <gray>当前在线：{online_count}/{max_players}</gray>
        <gold>================================</gold>
    server-switch:
      default: "<gold>⭐ VIP {player} 从 <yellow>{from}</yellow> 切换到 <yellow>{to}</yellow></gold>"